apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: hwmux-clinet-golang
  title: Hwmux Client Golang
  description: Hwmux Client Golang
spec:
  type: library
  lifecycle: production
  owner: group:sg.infrasw_fs_dev
  system: hwmux
