/*
HW Mux Reservation System

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.36.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hwmux

import (
	"encoding/json"
	"fmt"
)

// LogResourceType - struct for LogResourceType
type LogResourceType struct {
	BlankEnum *BlankEnum
	NullEnum *NullEnum
	ResourceTypeEnum *ResourceTypeEnum
}

// BlankEnumAsLogResourceType is a convenience function that returns BlankEnum wrapped in LogResourceType
func BlankEnumAsLogResourceType(v *BlankEnum) LogResourceType {
	return LogResourceType{
		BlankEnum: v,
	}
}

// NullEnumAsLogResourceType is a convenience function that returns NullEnum wrapped in LogResourceType
func NullEnumAsLogResourceType(v *NullEnum) LogResourceType {
	return LogResourceType{
		NullEnum: v,
	}
}

// ResourceTypeEnumAsLogResourceType is a convenience function that returns ResourceTypeEnum wrapped in LogResourceType
func ResourceTypeEnumAsLogResourceType(v *ResourceTypeEnum) LogResourceType {
	return LogResourceType{
		ResourceTypeEnum: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *LogResourceType) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BlankEnum
	err = newStrictDecoder(data).Decode(&dst.BlankEnum)
	if err == nil {
		jsonBlankEnum, _ := json.Marshal(dst.BlankEnum)
		if string(jsonBlankEnum) == "{}" { // empty struct
			dst.BlankEnum = nil
		} else {
			match++
		}
	} else {
		dst.BlankEnum = nil
	}

	// try to unmarshal data into NullEnum
	err = newStrictDecoder(data).Decode(&dst.NullEnum)
	if err == nil {
		jsonNullEnum, _ := json.Marshal(dst.NullEnum)
		if string(jsonNullEnum) == "{}" { // empty struct
			dst.NullEnum = nil
		} else {
			match++
		}
	} else {
		dst.NullEnum = nil
	}

	// try to unmarshal data into ResourceTypeEnum
	err = newStrictDecoder(data).Decode(&dst.ResourceTypeEnum)
	if err == nil {
		jsonResourceTypeEnum, _ := json.Marshal(dst.ResourceTypeEnum)
		if string(jsonResourceTypeEnum) == "{}" { // empty struct
			dst.ResourceTypeEnum = nil
		} else {
			match++
		}
	} else {
		dst.ResourceTypeEnum = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BlankEnum = nil
		dst.NullEnum = nil
		dst.ResourceTypeEnum = nil

		return fmt.Errorf("data matches more than one schema in oneOf(LogResourceType)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(LogResourceType)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src LogResourceType) MarshalJSON() ([]byte, error) {
	if src.BlankEnum != nil {
		return json.Marshal(&src.BlankEnum)
	}

	if src.NullEnum != nil {
		return json.Marshal(&src.NullEnum)
	}

	if src.ResourceTypeEnum != nil {
		return json.Marshal(&src.ResourceTypeEnum)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *LogResourceType) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BlankEnum != nil {
		return obj.BlankEnum
	}

	if obj.NullEnum != nil {
		return obj.NullEnum
	}

	if obj.ResourceTypeEnum != nil {
		return obj.ResourceTypeEnum
	}

	// all schemas are nil
	return nil
}

type NullableLogResourceType struct {
	value *LogResourceType
	isSet bool
}

func (v NullableLogResourceType) Get() *LogResourceType {
	return v.value
}

func (v *NullableLogResourceType) Set(val *LogResourceType) {
	v.value = val
	v.isSet = true
}

func (v NullableLogResourceType) IsSet() bool {
	return v.isSet
}

func (v *NullableLogResourceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogResourceType(val *LogResourceType) *NullableLogResourceType {
	return &NullableLogResourceType{value: val, isSet: true}
}

func (v NullableLogResourceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogResourceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


